### ISSUE TITLE
Create Dev Env at GitHub Codespaces

### ISSUE THREAD

**Issue by conti0513** [conti0513/development_public#10]
## 概要

クラウド環境でPythonコードを開発し、ローカルマシンでコンテナをダウンロードして実行するためのモダンな開発環境を設定します。
このIssueでは、GitHub Codespacesを使用して開発し、GitHub Actionsを利用してDockerイメージを自動的にビルドおよびプッシュし、ローカルマシンで実行できるようにします。

### クラウド環境 (GitHub Codespaces)

1. **プロジェクトの準備**
    - コードを開発し、GitHubリポジトリにプッシュします。

2. **Dockerfileの作成**
    - プロジェクトのルートディレクトリに以下の内容のDockerfileを作成します。

    ```Dockerfile
    FROM python:3.9-slim
    WORKDIR /app
    COPY requirements.txt .
    RUN pip install --no-cache-dir -r requirements.txt
    COPY . .
    CMD ["python", "app.py"]
    ```

3. **app.pyの作成**
    - `app.py`ファイルを作成し、以下の内容を記述します。

    ```python
    print("Hello World")
    ```

4. **requirements.txtの作成**
    - 必要な場合は、依存関係を記述します。

5. **GitHub Actionsワークフローの設定**
    - `.github/workflows/docker-publish.yml`を作成し、以下の内容を記述します。

    ```yaml
    name: Build and Push Docker Image

    on:
      push:
        branches:
          - main

    jobs:
      build-and-push:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v2

          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build and push
            uses: docker/build-push-action@v2
            with:
              context: .
              push: true
              tags: your-dockerhub-username/my-python-app:latest
    ```

6. **GitHub Secretsの設定**
    - `DOCKER_USERNAME`と`DOCKER_PASSWORD`を設定します。

### ローカル環境 (Mac)

1. **作業ディレクトリの作成**

    ```sh
    mkdir -p /Users/yoshi/Development/workdir
    cd /Users/yoshi/Development/workdir
    ```

2. **Dockerイメージのプル**

    ```sh
    docker pull your-dockerhub-username/my-python-app:latest
    ```

3. **Dockerコンテナの実行**

    ```sh
    docker run --rm your-dockerhub-username/my-python-app:latest
    ```

## 目的

- クラウド上での開発とバージョン管理を効率化
- CI/CDパイプラインの自動化
- ローカル環境の依存関係を最小化し、効率的に最新のコードを実行可能にする
```

3. **Assigneesを設定**
   - 自分自身をアサインします（任意）。

4. **Labelsを設定**
   - `enhancement`や`task`などの適切なラベルを追加します（任意）。

### ステップ 4: Issueの作成

1. **Issueを作成**
   - 「Submit new issue」ボタンをクリックしてIssueを作成します。

### まとめ

これで、GitHub Issuesを使用して、明日の開発タスクを整理し、進行状況を追跡することができます。Issueを使ってタスクを管理することで、作業の見通しが立ちやすくなり、効率的に開発を進めることができます。
